config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "posts#index"
  resources :users, only: [:edit, :update, :show]
  resources :posts do
    #コメント機能
    resources :comments, only: [:create, :destroy]
    #いいね機能
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/views/shared/_header.html.haml
.headernav
  .headeruppercontent
    .headeruppercontent__title
      %i.fa.fa-plane
      = link_to "Tripper",root_path
    .headersearch
      = render "./shared/search"
  .headerundercontent
    .headerusericon
      %text
        = current_user&.name
    .headerundercontent__btn
      - if user_signed_in?
        .headerundercontent__btn--logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        .headerundercontent__btn--mypage
          = link_to "マイページ", "/users/#{current_user.id}"
        .headerundercontent__btn--edit
          = link_to "アカウント編集", edit_user_path(current_user)
      - else
        .headerundercontent__btn--logout
          = link_to "ログイン", user_session_path, class: 'post'
        .headerundercontent__btn--logout
          = link_to "新規登録", new_user_registration_path, class: 'post'

app/views/shared/_postsbtn.html.haml
- if user_signed_in?
  = link_to '/posts/new', class: 'Exhibition__btn' do
    .Exhibition__btn--text
      投稿する
    

app/views/shared/_postszone.html.haml
.contentswrapper
  - @posts.each do |post|
    .contents
      .uppercontents
        .uppercontents__usericon
          %text
          = post.user.name
        .uppercontents__more
        - if user_signed_in?
          .menubar
            %label
              %i.fa.fa-ellipsis-h
              %input.acordion{:id => "list", :type => "checkbox"}
              %ul
                %li
                  = link_to '詳細', "/posts/#{post.id}", method: :get
                - if user_signed_in? && current_user.id == post.user_id
                  -# %li
                  -#   = link_to '編集', "/posts/#{post.id}/edit", method: :get
                  %li
                    = link_to '削除', "/posts/#{post.id}", method: :delete
      .contents__country
        %a
          = post.country
        .slider
          - post.images.each do |image|
            = image_tag image.image_url
      .undercontents
        .undercontentsupper
          .counts
            .undercontentsupper__likecount
              %i.fa.fa-thumbs-up
              = post.liked_users.count
            .undercontentsupper__commentcount
              %i.fa.fa-envelope
              = post.comments.count
          .undercontentsupper__time
            %i.fa.fa-clock
            = post.created_at.strftime("%Y-%m-%d")
        .undercontents__travelexpense
          %i.fa.fa-yen-sign
          = post.travelexpense
          円
        .undercontents__dates
          %i.fa.fa-calendar
          = post.tdate
          〜
          = post.fdate
        .undercontents__post
          = post.content

app/views/shared/_search.html.haml
.searchwrapper
  .searchzone
    .searchzone__input
      = form_tag(search_posts_path,:method => 'get') do
        = text_field_tag :keyword, "", placeholder: "旅行先検索 例：沖縄", class: "search-input" 
        = submit_tag '検索', class: "search-submit" 
        