config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root "posts#index"
  resources :users, only: [:edit, :update, :show]
  resources :posts do
    #コメント機能
    resources :comments, only: [:create, :destroy]
    #いいね機能
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image,ImageUploader
  validates :content, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy#いいね機能
  has_many :liked_users, through: :likes, source: :user#いいね機能
  has_many :comments, dependent: :destroy#コメント機能
  has_many :images, dependent: :destroy 
  accepts_nested_attributes_for :images, allow_destroy: true#画像複数投稿

  def self.search(search)
    return Post.all unless search
    Post.where('country LIKE(?)', "%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    # binding.pry
    @post = Post.new
    @post.images.build
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    #いいね機能
    @like = Like.new
    #コメント機能
    @comments = @post.comments
    @comment = Comment.new
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:name, :content, :country, :travelexpense, :tdate, :fdate, images_attributes: [:image_url, :_destroy, :id]).merge(user_id: current_user.id)
  end

end

app/views/posts/_postszone.html.haml
.contentswrapper
  - @posts.each do |post|
    .contents
      .uppercontents
        .uppercontents__usericon
          %text
          = post.user.name
        .uppercontents__more
          %ul.more_list
            %li
              = link_to '詳細', "/posts/#{post.id}", method: :get
            %li
              = link_to '編集', "/posts/#{post.id}/edit", method: :get
            %li
              = link_to '削除', "/posts/#{post.id}", method: :delete
            %li
      = image_tag post.image.url
      .contents__post
        = simple_format(post.content)
        -# %span.name
        -# %a{:href => "/users/#{post.user.id}"}
        -#   %span 投稿者
        -#   = post.user.name

app/views/posts/edit.html.haml
= render "./shared/header"
.formwrapper
  .form
    = form_for [@post] do |f|
      .form__mask
        .form__mask__image
          #image-box-1
            .post-num-0#image-box__container
              .input-area
                = f.fields_for :images do |i|
                  %label{for: "img-file"}
                    %i.fas.fa-camera
                  = i.file_field :image_url, type: 'file', name: "post[images_attributes][][image_url]", value:"", style: "display:none", id:"img-file"
      = f.text_field :country, class: 'form__country', placeholder: '旅行先'
      = f.select :travelexpense, [['~9999', '~9999'], ['10000~19999', '10000~19999'], ['20000~29999', '20000~29999'], ['30000~39999', '30000~39999'], ['40000~49999', '40000~49999'], ['50000~59999', '50000~59999'], ['60000~69999', '60000~69999'], ['70000~79999', '70000~79999'], ['80000~89999', '80000~89999'], ['90000~99999', '90000~99999'], ['100000~', '100000~']], prompt: "旅行費を選択してください"
      = f.text_field :content, class: 'form__message', placeholder: '旅行の思い出'
      = f.submit 'Send', class: 'form__submit'

app/views/posts/index.html.haml
.wrapper
  = render "./shared/header"
  = render "./shared/postszone"
  = render "./shared/postsbtn"
  

app/views/posts/new.html.haml
= render "./shared/header"
.formwrapper
  .form
    = form_for [@post] do |f|
      .form__mask
        .form__mask__image
          #image-box-1
            .post-num-0#image-box__container
              .input-area
                = f.fields_for :images do |i|
                  %label{for: "img-file"}
                    %i.fas.fa-camera
                  = i.file_field :image_url, type: 'file', name: "post[images_attributes][][image_url]", value:"", style: "display:none", id:"img-file"
        .form__mask__country
          %a
            旅行先
        = f.text_field :country, class: 'form__country'
        .form__mask__date
          %a
            旅行期間
        = f.date_field :tdate, class: 'form__startdate'
        〜
        = f.date_field :fdate, class: 'form__finishdate'
      = f.select :travelexpense, [['~9999', '~9999'], ['10000~19999', '10000~19999'], ['20000~29999', '20000~29999'], ['30000~39999', '30000~39999'], ['40000~49999', '40000~49999'], ['50000~59999', '50000~59999'], ['60000~69999', '60000~69999'], ['70000~79999', '70000~79999'], ['80000~89999', '80000~89999'], ['90000~99999', '90000~99999'], ['100000~', '100000~']], prompt: "旅行費を選択してください"
      = f.text_field :content, class: 'form__message', placeholder: '旅行の思い出'
      = f.submit 'Send', class: 'form__submit'

app/views/posts/search.html.haml
= render "./shared/header"
.contentswrapper
  - @posts.each do |post|
    .contents
      .uppercontents
        .uppercontents__usericon
          %text
          = post.user.name
        .uppercontents__more
          .menubar
            %label
              %i.fa.fa-ellipsis-h
              %input.acordion{:id => "list", :type => "checkbox"}
              %ul
                %li
                  = link_to '詳細', "/posts/#{post.id}", method: :get
                - if user_signed_in? && current_user.id == post.user_id
                  -# %li
                  -#   = link_to '編集', "/posts/#{post.id}/edit", method: :get
                  %li
                    = link_to '削除', "/posts/#{post.id}", method: :delete
      .contents__country
        %a
          = post.country
        .slider
          - post.images.each do |image|
            = image_tag image.image_url
      .undercontents
        .undercontentsupper
          .counts
            .undercontentsupper__likecount
              %i.fa.fa-thumbs-up
              = post.liked_users.count
            .undercontentsupper__commentcount
              %i.fa.fa-envelope
              = post.comments.count
          .undercontentsupper__time
            %i.fa.fa-clock
            = post.created_at.strftime("%Y-%m-%d")
        .undercontents__travelexpense
          %i.fa.fa-yen-sign
          = post.travelexpense
          円
        .undercontents__dates
          %i.fa.fa-calendar
          = post.tdate
          〜
          = post.fdate
        .undercontents__post
          = post.content

app/views/posts/show.html.haml
= render "./shared/header"
.contentswrapper
  .contents
    .uppercontents
      .uppercontents__usericon
        %text
        = @post.user.name
      .uppercontents__more
      - if user_signed_in?
        .menubar
          %label
            %i.fa.fa-ellipsis-h
            %input.acordion{:id => "list", :type => "checkbox"}
            %ul
              - if user_signed_in? && current_user.id == @post.user_id
                -# %li
                -#   = link_to '編集', "/posts/#{@post.id}/edit", method: :get
                %li
                  = link_to '削除', "/posts/#{@post.id}", method: :delete
    .contents__country
      %a
        = @post.country
      .slider
        - @post.images.each do |image|
          = image_tag image.image_url
    .undercontents
      .undercontentsupper
        .counts
          .undercontentsupper__likecount
            - if current_user.already_liked?(@post)
              = button_to post_like_path(@post), method: :delete do
                %i.fa.fa-thumbs-up
                = @post.likes.count 
            - else
              = button_to post_likes_path(@post) do
                %i.fa.fa-thumbs-up
                = @post.likes.count
          .undercontentsupper__commentcount
            %i.fa.fa-envelope
            = @post.comments.count 
        .undercontentsupper__time
          %i.fa.fa-clock
          = @post.created_at.strftime("%Y-%m-%d")
      .undercontents__travelexpense
        %i.fa.fa-yen-sign
        = @post.travelexpense
        円
      .undercontents__dates
        %i.fa.fa-calendar
        = @post.tdate
        〜
        = @post.fdate
      .undercontents__post
        = @post.content
  .contentscommments
    .contentscommments__show
      .title
        %h2 〈 コメント一覧 〉
      .inner
        - @comments.each do |comment|
          .innerupper
            .innerupper__name
              = comment.user.name
            ：
            .innerupper__content
              = comment.content
          .inner__time
            = comment.created_at.strftime("%Y-%m-%d")
      .contentscommments__form
        = form_for [@post, @comment] do |f|
          = f.text_field :content, placeholder: 'コメントを追加'
          %br= f.submit 'コメントする', class: 'commentbtn'